#!/bin/bash
# Script to generate individual test cases for each PNG file

set -e

echo "Generating individual test cases for each PNG file..."

# Output file for auto-generated PNG suite tests
output_file="test_pngcheck_suite.bats"

# Write the header for PNG suite tests
cat > "$output_file" << 'EOF'
#!/usr/bin/env bats
# This file is auto-generated by generate_test_cases.sh
# PNG Suite tests - DO NOT EDIT MANUALLY

load 'helpers/test_helpers'
load 'libs/bats-support/load.bash'
load 'libs/bats-assert/load.bash'

setup_file() {
    download_pngsuite_if_needed
}

# === AUTO-GENERATED PNG SUITE TESTS ===
# Do not edit below this line - tests are auto-generated

EOF

# Generate individual test cases for each PNG file using the helper function
test_count=0
for expected_file in expectations/pngsuite/*.out; do
    [[ -f "$expected_file" ]] || continue

    basename=$(basename "$expected_file" .out)
    png_file="fixtures/pngsuite/$basename"

    if [[ -f "$png_file" ]]; then
        # Determine if this is a valid or invalid file based on expected output
        expected_content=$(cat "$expected_file")
        test_type="UNKNOWN"

        if [[ "$expected_content" == *"OK:"* ]]; then
            test_type="VALID"
        elif [[ "$expected_content" == *"ERROR:"* ]]; then
            test_type="INVALID"
        elif [[ "$expected_content" == *"WARN:"* ]]; then
            test_type="WARNING"
        fi

        # Write individual test case using the helper function
        cat >> "$output_file" << EOF
@test "[$test_type] $basename" {
    test_png_file "fixtures/pngsuite/$basename" "expectations/pngsuite/$basename.out"
}

EOF
        ((test_count++))
    fi
done

echo "Generated PNG suite test cases in $output_file"
echo "Total PNG suite test cases: $test_count"
echo ""
echo "Test files created:"
echo "  - tests/test_pngcheck_cli.bats (static CLI tests)"
echo "  - tests/test_pngcheck_suite.bats (auto-generated PNG suite tests)"
echo ""
echo "To run all tests: bats tests/test_pngcheck_*.bats"
echo "To run CLI tests only: bats tests/test_pngcheck_cli.bats"
echo "To run PNG suite tests only: bats tests/test_pngcheck_suite.bats"
