#!/usr/bin/env bats
# This file is auto-generated by generate_test_cases.sh
# PNG Suite tests - DO NOT EDIT MANUALLY

load 'helpers/test_helpers'
load 'libs/bats-support/load.bash'
load 'libs/bats-assert/load.bash'

setup_file() {
    download_pngsuite_if_needed
}

# === AUTO-GENERATED PNG SUITE TESTS ===
# Do not edit below this line - tests are auto-generated

@test "[VALID] basi0g01.png" {
    test_png_file "fixtures/pngsuite/basi0g01.png" "expectations/pngsuite/basi0g01.png.out"
}

@test "[VALID] basi0g02.png" {
    test_png_file "fixtures/pngsuite/basi0g02.png" "expectations/pngsuite/basi0g02.png.out"
}

@test "[VALID] basi0g04.png" {
    test_png_file "fixtures/pngsuite/basi0g04.png" "expectations/pngsuite/basi0g04.png.out"
}

@test "[VALID] basi0g08.png" {
    test_png_file "fixtures/pngsuite/basi0g08.png" "expectations/pngsuite/basi0g08.png.out"
}

@test "[VALID] basi0g16.png" {
    test_png_file "fixtures/pngsuite/basi0g16.png" "expectations/pngsuite/basi0g16.png.out"
}

@test "[VALID] basi2c08.png" {
    test_png_file "fixtures/pngsuite/basi2c08.png" "expectations/pngsuite/basi2c08.png.out"
}

@test "[VALID] basi2c16.png" {
    test_png_file "fixtures/pngsuite/basi2c16.png" "expectations/pngsuite/basi2c16.png.out"
}

@test "[VALID] basi3p01.png" {
    test_png_file "fixtures/pngsuite/basi3p01.png" "expectations/pngsuite/basi3p01.png.out"
}

@test "[VALID] basi3p02.png" {
    test_png_file "fixtures/pngsuite/basi3p02.png" "expectations/pngsuite/basi3p02.png.out"
}

@test "[VALID] basi3p04.png" {
    test_png_file "fixtures/pngsuite/basi3p04.png" "expectations/pngsuite/basi3p04.png.out"
}

@test "[VALID] basi3p08.png" {
    test_png_file "fixtures/pngsuite/basi3p08.png" "expectations/pngsuite/basi3p08.png.out"
}

@test "[VALID] basi4a08.png" {
    test_png_file "fixtures/pngsuite/basi4a08.png" "expectations/pngsuite/basi4a08.png.out"
}

@test "[VALID] basi4a16.png" {
    test_png_file "fixtures/pngsuite/basi4a16.png" "expectations/pngsuite/basi4a16.png.out"
}

@test "[VALID] basi6a08.png" {
    test_png_file "fixtures/pngsuite/basi6a08.png" "expectations/pngsuite/basi6a08.png.out"
}

@test "[VALID] basi6a16.png" {
    test_png_file "fixtures/pngsuite/basi6a16.png" "expectations/pngsuite/basi6a16.png.out"
}

@test "[VALID] basn0g01.png" {
    test_png_file "fixtures/pngsuite/basn0g01.png" "expectations/pngsuite/basn0g01.png.out"
}

@test "[VALID] basn0g02.png" {
    test_png_file "fixtures/pngsuite/basn0g02.png" "expectations/pngsuite/basn0g02.png.out"
}

@test "[VALID] basn0g04.png" {
    test_png_file "fixtures/pngsuite/basn0g04.png" "expectations/pngsuite/basn0g04.png.out"
}

@test "[VALID] basn0g08.png" {
    test_png_file "fixtures/pngsuite/basn0g08.png" "expectations/pngsuite/basn0g08.png.out"
}

@test "[VALID] basn0g16.png" {
    test_png_file "fixtures/pngsuite/basn0g16.png" "expectations/pngsuite/basn0g16.png.out"
}

@test "[VALID] basn2c08.png" {
    test_png_file "fixtures/pngsuite/basn2c08.png" "expectations/pngsuite/basn2c08.png.out"
}

@test "[VALID] basn2c16.png" {
    test_png_file "fixtures/pngsuite/basn2c16.png" "expectations/pngsuite/basn2c16.png.out"
}

@test "[VALID] basn3p01.png" {
    test_png_file "fixtures/pngsuite/basn3p01.png" "expectations/pngsuite/basn3p01.png.out"
}

@test "[VALID] basn3p02.png" {
    test_png_file "fixtures/pngsuite/basn3p02.png" "expectations/pngsuite/basn3p02.png.out"
}

@test "[VALID] basn3p04.png" {
    test_png_file "fixtures/pngsuite/basn3p04.png" "expectations/pngsuite/basn3p04.png.out"
}

@test "[VALID] basn3p08.png" {
    test_png_file "fixtures/pngsuite/basn3p08.png" "expectations/pngsuite/basn3p08.png.out"
}

@test "[VALID] basn4a08.png" {
    test_png_file "fixtures/pngsuite/basn4a08.png" "expectations/pngsuite/basn4a08.png.out"
}

@test "[VALID] basn4a16.png" {
    test_png_file "fixtures/pngsuite/basn4a16.png" "expectations/pngsuite/basn4a16.png.out"
}

@test "[VALID] basn6a08.png" {
    test_png_file "fixtures/pngsuite/basn6a08.png" "expectations/pngsuite/basn6a08.png.out"
}

@test "[VALID] basn6a16.png" {
    test_png_file "fixtures/pngsuite/basn6a16.png" "expectations/pngsuite/basn6a16.png.out"
}

@test "[VALID] bgai4a08.png" {
    test_png_file "fixtures/pngsuite/bgai4a08.png" "expectations/pngsuite/bgai4a08.png.out"
}

@test "[VALID] bgai4a16.png" {
    test_png_file "fixtures/pngsuite/bgai4a16.png" "expectations/pngsuite/bgai4a16.png.out"
}

@test "[VALID] bgan6a08.png" {
    test_png_file "fixtures/pngsuite/bgan6a08.png" "expectations/pngsuite/bgan6a08.png.out"
}

@test "[VALID] bgan6a16.png" {
    test_png_file "fixtures/pngsuite/bgan6a16.png" "expectations/pngsuite/bgan6a16.png.out"
}

@test "[VALID] bgbn4a08.png" {
    test_png_file "fixtures/pngsuite/bgbn4a08.png" "expectations/pngsuite/bgbn4a08.png.out"
}

@test "[VALID] bggn4a16.png" {
    test_png_file "fixtures/pngsuite/bggn4a16.png" "expectations/pngsuite/bggn4a16.png.out"
}

@test "[VALID] bgwn6a08.png" {
    test_png_file "fixtures/pngsuite/bgwn6a08.png" "expectations/pngsuite/bgwn6a08.png.out"
}

@test "[VALID] bgyn6a16.png" {
    test_png_file "fixtures/pngsuite/bgyn6a16.png" "expectations/pngsuite/bgyn6a16.png.out"
}

@test "[VALID] ccwn2c08.png" {
    test_png_file "fixtures/pngsuite/ccwn2c08.png" "expectations/pngsuite/ccwn2c08.png.out"
}

@test "[VALID] ccwn3p08.png" {
    test_png_file "fixtures/pngsuite/ccwn3p08.png" "expectations/pngsuite/ccwn3p08.png.out"
}

@test "[VALID] cdfn2c08.png" {
    test_png_file "fixtures/pngsuite/cdfn2c08.png" "expectations/pngsuite/cdfn2c08.png.out"
}

@test "[VALID] cdhn2c08.png" {
    test_png_file "fixtures/pngsuite/cdhn2c08.png" "expectations/pngsuite/cdhn2c08.png.out"
}

@test "[VALID] cdsn2c08.png" {
    test_png_file "fixtures/pngsuite/cdsn2c08.png" "expectations/pngsuite/cdsn2c08.png.out"
}

@test "[VALID] cdun2c08.png" {
    test_png_file "fixtures/pngsuite/cdun2c08.png" "expectations/pngsuite/cdun2c08.png.out"
}

@test "[VALID] ch1n3p04.png" {
    test_png_file "fixtures/pngsuite/ch1n3p04.png" "expectations/pngsuite/ch1n3p04.png.out"
}

@test "[VALID] ch2n3p08.png" {
    test_png_file "fixtures/pngsuite/ch2n3p08.png" "expectations/pngsuite/ch2n3p08.png.out"
}

@test "[VALID] cm0n0g04.png" {
    test_png_file "fixtures/pngsuite/cm0n0g04.png" "expectations/pngsuite/cm0n0g04.png.out"
}

@test "[INVALID] cm7n0g04.png" {
    test_png_file "fixtures/pngsuite/cm7n0g04.png" "expectations/pngsuite/cm7n0g04.png.out"
}

@test "[VALID] cm9n0g04.png" {
    test_png_file "fixtures/pngsuite/cm9n0g04.png" "expectations/pngsuite/cm9n0g04.png.out"
}

@test "[VALID] cs3n2c16.png" {
    test_png_file "fixtures/pngsuite/cs3n2c16.png" "expectations/pngsuite/cs3n2c16.png.out"
}

@test "[VALID] cs3n3p08.png" {
    test_png_file "fixtures/pngsuite/cs3n3p08.png" "expectations/pngsuite/cs3n3p08.png.out"
}

@test "[VALID] cs5n2c08.png" {
    test_png_file "fixtures/pngsuite/cs5n2c08.png" "expectations/pngsuite/cs5n2c08.png.out"
}

@test "[VALID] cs5n3p08.png" {
    test_png_file "fixtures/pngsuite/cs5n3p08.png" "expectations/pngsuite/cs5n3p08.png.out"
}

@test "[VALID] cs8n2c08.png" {
    test_png_file "fixtures/pngsuite/cs8n2c08.png" "expectations/pngsuite/cs8n2c08.png.out"
}

@test "[VALID] cs8n3p08.png" {
    test_png_file "fixtures/pngsuite/cs8n3p08.png" "expectations/pngsuite/cs8n3p08.png.out"
}

@test "[VALID] ct0n0g04.png" {
    test_png_file "fixtures/pngsuite/ct0n0g04.png" "expectations/pngsuite/ct0n0g04.png.out"
}

@test "[VALID] ct1n0g04.png" {
    test_png_file "fixtures/pngsuite/ct1n0g04.png" "expectations/pngsuite/ct1n0g04.png.out"
}

@test "[VALID] cten0g04.png" {
    test_png_file "fixtures/pngsuite/cten0g04.png" "expectations/pngsuite/cten0g04.png.out"
}

@test "[VALID] ctfn0g04.png" {
    test_png_file "fixtures/pngsuite/ctfn0g04.png" "expectations/pngsuite/ctfn0g04.png.out"
}

@test "[VALID] ctgn0g04.png" {
    test_png_file "fixtures/pngsuite/ctgn0g04.png" "expectations/pngsuite/ctgn0g04.png.out"
}

@test "[VALID] cthn0g04.png" {
    test_png_file "fixtures/pngsuite/cthn0g04.png" "expectations/pngsuite/cthn0g04.png.out"
}

@test "[VALID] ctjn0g04.png" {
    test_png_file "fixtures/pngsuite/ctjn0g04.png" "expectations/pngsuite/ctjn0g04.png.out"
}

@test "[VALID] ctzn0g04.png" {
    test_png_file "fixtures/pngsuite/ctzn0g04.png" "expectations/pngsuite/ctzn0g04.png.out"
}

@test "[VALID] exif2c08.png" {
    test_png_file "fixtures/pngsuite/exif2c08.png" "expectations/pngsuite/exif2c08.png.out"
}

@test "[VALID] f00n0g08.png" {
    test_png_file "fixtures/pngsuite/f00n0g08.png" "expectations/pngsuite/f00n0g08.png.out"
}

@test "[VALID] f00n2c08.png" {
    test_png_file "fixtures/pngsuite/f00n2c08.png" "expectations/pngsuite/f00n2c08.png.out"
}

@test "[VALID] f01n0g08.png" {
    test_png_file "fixtures/pngsuite/f01n0g08.png" "expectations/pngsuite/f01n0g08.png.out"
}

@test "[VALID] f01n2c08.png" {
    test_png_file "fixtures/pngsuite/f01n2c08.png" "expectations/pngsuite/f01n2c08.png.out"
}

@test "[VALID] f02n0g08.png" {
    test_png_file "fixtures/pngsuite/f02n0g08.png" "expectations/pngsuite/f02n0g08.png.out"
}

@test "[VALID] f02n2c08.png" {
    test_png_file "fixtures/pngsuite/f02n2c08.png" "expectations/pngsuite/f02n2c08.png.out"
}

@test "[VALID] f03n0g08.png" {
    test_png_file "fixtures/pngsuite/f03n0g08.png" "expectations/pngsuite/f03n0g08.png.out"
}

@test "[VALID] f03n2c08.png" {
    test_png_file "fixtures/pngsuite/f03n2c08.png" "expectations/pngsuite/f03n2c08.png.out"
}

@test "[VALID] f04n0g08.png" {
    test_png_file "fixtures/pngsuite/f04n0g08.png" "expectations/pngsuite/f04n0g08.png.out"
}

@test "[VALID] f04n2c08.png" {
    test_png_file "fixtures/pngsuite/f04n2c08.png" "expectations/pngsuite/f04n2c08.png.out"
}

@test "[VALID] f99n0g04.png" {
    test_png_file "fixtures/pngsuite/f99n0g04.png" "expectations/pngsuite/f99n0g04.png.out"
}

@test "[VALID] g03n0g16.png" {
    test_png_file "fixtures/pngsuite/g03n0g16.png" "expectations/pngsuite/g03n0g16.png.out"
}

@test "[VALID] g03n2c08.png" {
    test_png_file "fixtures/pngsuite/g03n2c08.png" "expectations/pngsuite/g03n2c08.png.out"
}

@test "[VALID] g03n3p04.png" {
    test_png_file "fixtures/pngsuite/g03n3p04.png" "expectations/pngsuite/g03n3p04.png.out"
}

@test "[VALID] g04n0g16.png" {
    test_png_file "fixtures/pngsuite/g04n0g16.png" "expectations/pngsuite/g04n0g16.png.out"
}

@test "[VALID] g04n2c08.png" {
    test_png_file "fixtures/pngsuite/g04n2c08.png" "expectations/pngsuite/g04n2c08.png.out"
}

@test "[VALID] g04n3p04.png" {
    test_png_file "fixtures/pngsuite/g04n3p04.png" "expectations/pngsuite/g04n3p04.png.out"
}

@test "[VALID] g05n0g16.png" {
    test_png_file "fixtures/pngsuite/g05n0g16.png" "expectations/pngsuite/g05n0g16.png.out"
}

@test "[VALID] g05n2c08.png" {
    test_png_file "fixtures/pngsuite/g05n2c08.png" "expectations/pngsuite/g05n2c08.png.out"
}

@test "[VALID] g05n3p04.png" {
    test_png_file "fixtures/pngsuite/g05n3p04.png" "expectations/pngsuite/g05n3p04.png.out"
}

@test "[VALID] g07n0g16.png" {
    test_png_file "fixtures/pngsuite/g07n0g16.png" "expectations/pngsuite/g07n0g16.png.out"
}

@test "[VALID] g07n2c08.png" {
    test_png_file "fixtures/pngsuite/g07n2c08.png" "expectations/pngsuite/g07n2c08.png.out"
}

@test "[VALID] g07n3p04.png" {
    test_png_file "fixtures/pngsuite/g07n3p04.png" "expectations/pngsuite/g07n3p04.png.out"
}

@test "[VALID] g10n0g16.png" {
    test_png_file "fixtures/pngsuite/g10n0g16.png" "expectations/pngsuite/g10n0g16.png.out"
}

@test "[VALID] g10n2c08.png" {
    test_png_file "fixtures/pngsuite/g10n2c08.png" "expectations/pngsuite/g10n2c08.png.out"
}

@test "[VALID] g10n3p04.png" {
    test_png_file "fixtures/pngsuite/g10n3p04.png" "expectations/pngsuite/g10n3p04.png.out"
}

@test "[VALID] g25n0g16.png" {
    test_png_file "fixtures/pngsuite/g25n0g16.png" "expectations/pngsuite/g25n0g16.png.out"
}

@test "[VALID] g25n2c08.png" {
    test_png_file "fixtures/pngsuite/g25n2c08.png" "expectations/pngsuite/g25n2c08.png.out"
}

@test "[VALID] g25n3p04.png" {
    test_png_file "fixtures/pngsuite/g25n3p04.png" "expectations/pngsuite/g25n3p04.png.out"
}

@test "[VALID] oi1n0g16.png" {
    test_png_file "fixtures/pngsuite/oi1n0g16.png" "expectations/pngsuite/oi1n0g16.png.out"
}

@test "[VALID] oi1n2c16.png" {
    test_png_file "fixtures/pngsuite/oi1n2c16.png" "expectations/pngsuite/oi1n2c16.png.out"
}

@test "[VALID] oi2n0g16.png" {
    test_png_file "fixtures/pngsuite/oi2n0g16.png" "expectations/pngsuite/oi2n0g16.png.out"
}

@test "[VALID] oi2n2c16.png" {
    test_png_file "fixtures/pngsuite/oi2n2c16.png" "expectations/pngsuite/oi2n2c16.png.out"
}

@test "[VALID] oi4n0g16.png" {
    test_png_file "fixtures/pngsuite/oi4n0g16.png" "expectations/pngsuite/oi4n0g16.png.out"
}

@test "[VALID] oi4n2c16.png" {
    test_png_file "fixtures/pngsuite/oi4n2c16.png" "expectations/pngsuite/oi4n2c16.png.out"
}

@test "[VALID] oi9n0g16.png" {
    test_png_file "fixtures/pngsuite/oi9n0g16.png" "expectations/pngsuite/oi9n0g16.png.out"
}

@test "[VALID] oi9n2c16.png" {
    test_png_file "fixtures/pngsuite/oi9n2c16.png" "expectations/pngsuite/oi9n2c16.png.out"
}

@test "[VALID] PngSuite.png" {
    test_png_file "fixtures/pngsuite/PngSuite.png" "expectations/pngsuite/PngSuite.png.out"
}

@test "[VALID] pp0n2c16.png" {
    test_png_file "fixtures/pngsuite/pp0n2c16.png" "expectations/pngsuite/pp0n2c16.png.out"
}

@test "[VALID] pp0n6a08.png" {
    test_png_file "fixtures/pngsuite/pp0n6a08.png" "expectations/pngsuite/pp0n6a08.png.out"
}

@test "[VALID] ps1n0g08.png" {
    test_png_file "fixtures/pngsuite/ps1n0g08.png" "expectations/pngsuite/ps1n0g08.png.out"
}

@test "[VALID] ps1n2c16.png" {
    test_png_file "fixtures/pngsuite/ps1n2c16.png" "expectations/pngsuite/ps1n2c16.png.out"
}

@test "[VALID] ps2n0g08.png" {
    test_png_file "fixtures/pngsuite/ps2n0g08.png" "expectations/pngsuite/ps2n0g08.png.out"
}

@test "[VALID] ps2n2c16.png" {
    test_png_file "fixtures/pngsuite/ps2n2c16.png" "expectations/pngsuite/ps2n2c16.png.out"
}

@test "[VALID] s01i3p01.png" {
    test_png_file "fixtures/pngsuite/s01i3p01.png" "expectations/pngsuite/s01i3p01.png.out"
}

@test "[VALID] s01n3p01.png" {
    test_png_file "fixtures/pngsuite/s01n3p01.png" "expectations/pngsuite/s01n3p01.png.out"
}

@test "[VALID] s02i3p01.png" {
    test_png_file "fixtures/pngsuite/s02i3p01.png" "expectations/pngsuite/s02i3p01.png.out"
}

@test "[VALID] s02n3p01.png" {
    test_png_file "fixtures/pngsuite/s02n3p01.png" "expectations/pngsuite/s02n3p01.png.out"
}

@test "[VALID] s03i3p01.png" {
    test_png_file "fixtures/pngsuite/s03i3p01.png" "expectations/pngsuite/s03i3p01.png.out"
}

@test "[VALID] s03n3p01.png" {
    test_png_file "fixtures/pngsuite/s03n3p01.png" "expectations/pngsuite/s03n3p01.png.out"
}

@test "[VALID] s04i3p01.png" {
    test_png_file "fixtures/pngsuite/s04i3p01.png" "expectations/pngsuite/s04i3p01.png.out"
}

@test "[VALID] s04n3p01.png" {
    test_png_file "fixtures/pngsuite/s04n3p01.png" "expectations/pngsuite/s04n3p01.png.out"
}

@test "[VALID] s05i3p02.png" {
    test_png_file "fixtures/pngsuite/s05i3p02.png" "expectations/pngsuite/s05i3p02.png.out"
}

@test "[VALID] s05n3p02.png" {
    test_png_file "fixtures/pngsuite/s05n3p02.png" "expectations/pngsuite/s05n3p02.png.out"
}

@test "[VALID] s06i3p02.png" {
    test_png_file "fixtures/pngsuite/s06i3p02.png" "expectations/pngsuite/s06i3p02.png.out"
}

@test "[VALID] s06n3p02.png" {
    test_png_file "fixtures/pngsuite/s06n3p02.png" "expectations/pngsuite/s06n3p02.png.out"
}

@test "[VALID] s07i3p02.png" {
    test_png_file "fixtures/pngsuite/s07i3p02.png" "expectations/pngsuite/s07i3p02.png.out"
}

@test "[VALID] s07n3p02.png" {
    test_png_file "fixtures/pngsuite/s07n3p02.png" "expectations/pngsuite/s07n3p02.png.out"
}

@test "[VALID] s08i3p02.png" {
    test_png_file "fixtures/pngsuite/s08i3p02.png" "expectations/pngsuite/s08i3p02.png.out"
}

@test "[VALID] s08n3p02.png" {
    test_png_file "fixtures/pngsuite/s08n3p02.png" "expectations/pngsuite/s08n3p02.png.out"
}

@test "[VALID] s09i3p02.png" {
    test_png_file "fixtures/pngsuite/s09i3p02.png" "expectations/pngsuite/s09i3p02.png.out"
}

@test "[VALID] s09n3p02.png" {
    test_png_file "fixtures/pngsuite/s09n3p02.png" "expectations/pngsuite/s09n3p02.png.out"
}

@test "[VALID] s32i3p04.png" {
    test_png_file "fixtures/pngsuite/s32i3p04.png" "expectations/pngsuite/s32i3p04.png.out"
}

@test "[VALID] s32n3p04.png" {
    test_png_file "fixtures/pngsuite/s32n3p04.png" "expectations/pngsuite/s32n3p04.png.out"
}

@test "[VALID] s33i3p04.png" {
    test_png_file "fixtures/pngsuite/s33i3p04.png" "expectations/pngsuite/s33i3p04.png.out"
}

@test "[VALID] s33n3p04.png" {
    test_png_file "fixtures/pngsuite/s33n3p04.png" "expectations/pngsuite/s33n3p04.png.out"
}

@test "[VALID] s34i3p04.png" {
    test_png_file "fixtures/pngsuite/s34i3p04.png" "expectations/pngsuite/s34i3p04.png.out"
}

@test "[VALID] s34n3p04.png" {
    test_png_file "fixtures/pngsuite/s34n3p04.png" "expectations/pngsuite/s34n3p04.png.out"
}

@test "[VALID] s35i3p04.png" {
    test_png_file "fixtures/pngsuite/s35i3p04.png" "expectations/pngsuite/s35i3p04.png.out"
}

@test "[VALID] s35n3p04.png" {
    test_png_file "fixtures/pngsuite/s35n3p04.png" "expectations/pngsuite/s35n3p04.png.out"
}

@test "[VALID] s36i3p04.png" {
    test_png_file "fixtures/pngsuite/s36i3p04.png" "expectations/pngsuite/s36i3p04.png.out"
}

@test "[VALID] s36n3p04.png" {
    test_png_file "fixtures/pngsuite/s36n3p04.png" "expectations/pngsuite/s36n3p04.png.out"
}

@test "[VALID] s37i3p04.png" {
    test_png_file "fixtures/pngsuite/s37i3p04.png" "expectations/pngsuite/s37i3p04.png.out"
}

@test "[VALID] s37n3p04.png" {
    test_png_file "fixtures/pngsuite/s37n3p04.png" "expectations/pngsuite/s37n3p04.png.out"
}

@test "[VALID] s38i3p04.png" {
    test_png_file "fixtures/pngsuite/s38i3p04.png" "expectations/pngsuite/s38i3p04.png.out"
}

@test "[VALID] s38n3p04.png" {
    test_png_file "fixtures/pngsuite/s38n3p04.png" "expectations/pngsuite/s38n3p04.png.out"
}

@test "[VALID] s39i3p04.png" {
    test_png_file "fixtures/pngsuite/s39i3p04.png" "expectations/pngsuite/s39i3p04.png.out"
}

@test "[VALID] s39n3p04.png" {
    test_png_file "fixtures/pngsuite/s39n3p04.png" "expectations/pngsuite/s39n3p04.png.out"
}

@test "[VALID] s40i3p04.png" {
    test_png_file "fixtures/pngsuite/s40i3p04.png" "expectations/pngsuite/s40i3p04.png.out"
}

@test "[VALID] s40n3p04.png" {
    test_png_file "fixtures/pngsuite/s40n3p04.png" "expectations/pngsuite/s40n3p04.png.out"
}

@test "[VALID] tbbn0g04.png" {
    test_png_file "fixtures/pngsuite/tbbn0g04.png" "expectations/pngsuite/tbbn0g04.png.out"
}

@test "[VALID] tbbn2c16.png" {
    test_png_file "fixtures/pngsuite/tbbn2c16.png" "expectations/pngsuite/tbbn2c16.png.out"
}

@test "[VALID] tbbn3p08.png" {
    test_png_file "fixtures/pngsuite/tbbn3p08.png" "expectations/pngsuite/tbbn3p08.png.out"
}

@test "[VALID] tbgn2c16.png" {
    test_png_file "fixtures/pngsuite/tbgn2c16.png" "expectations/pngsuite/tbgn2c16.png.out"
}

@test "[VALID] tbgn3p08.png" {
    test_png_file "fixtures/pngsuite/tbgn3p08.png" "expectations/pngsuite/tbgn3p08.png.out"
}

@test "[VALID] tbrn2c08.png" {
    test_png_file "fixtures/pngsuite/tbrn2c08.png" "expectations/pngsuite/tbrn2c08.png.out"
}

@test "[VALID] tbwn0g16.png" {
    test_png_file "fixtures/pngsuite/tbwn0g16.png" "expectations/pngsuite/tbwn0g16.png.out"
}

@test "[VALID] tbwn3p08.png" {
    test_png_file "fixtures/pngsuite/tbwn3p08.png" "expectations/pngsuite/tbwn3p08.png.out"
}

@test "[VALID] tbyn3p08.png" {
    test_png_file "fixtures/pngsuite/tbyn3p08.png" "expectations/pngsuite/tbyn3p08.png.out"
}

@test "[VALID] tm3n3p02.png" {
    test_png_file "fixtures/pngsuite/tm3n3p02.png" "expectations/pngsuite/tm3n3p02.png.out"
}

@test "[VALID] tp0n0g08.png" {
    test_png_file "fixtures/pngsuite/tp0n0g08.png" "expectations/pngsuite/tp0n0g08.png.out"
}

@test "[VALID] tp0n2c08.png" {
    test_png_file "fixtures/pngsuite/tp0n2c08.png" "expectations/pngsuite/tp0n2c08.png.out"
}

@test "[VALID] tp0n3p08.png" {
    test_png_file "fixtures/pngsuite/tp0n3p08.png" "expectations/pngsuite/tp0n3p08.png.out"
}

@test "[VALID] tp1n3p08.png" {
    test_png_file "fixtures/pngsuite/tp1n3p08.png" "expectations/pngsuite/tp1n3p08.png.out"
}

@test "[INVALID] xc1n0g08.png" {
    test_png_file "fixtures/pngsuite/xc1n0g08.png" "expectations/pngsuite/xc1n0g08.png.out"
}

@test "[INVALID] xc9n2c08.png" {
    test_png_file "fixtures/pngsuite/xc9n2c08.png" "expectations/pngsuite/xc9n2c08.png.out"
}

@test "[INVALID] xcrn0g04.png" {
    test_png_file "fixtures/pngsuite/xcrn0g04.png" "expectations/pngsuite/xcrn0g04.png.out"
}

@test "[INVALID] xcsn0g01.png" {
    test_png_file "fixtures/pngsuite/xcsn0g01.png" "expectations/pngsuite/xcsn0g01.png.out"
}

@test "[INVALID] xd0n2c08.png" {
    test_png_file "fixtures/pngsuite/xd0n2c08.png" "expectations/pngsuite/xd0n2c08.png.out"
}

@test "[INVALID] xd3n2c08.png" {
    test_png_file "fixtures/pngsuite/xd3n2c08.png" "expectations/pngsuite/xd3n2c08.png.out"
}

@test "[INVALID] xd9n2c08.png" {
    test_png_file "fixtures/pngsuite/xd9n2c08.png" "expectations/pngsuite/xd9n2c08.png.out"
}

@test "[INVALID] xdtn0g01.png" {
    test_png_file "fixtures/pngsuite/xdtn0g01.png" "expectations/pngsuite/xdtn0g01.png.out"
}

@test "[INVALID] xhdn0g08.png" {
    test_png_file "fixtures/pngsuite/xhdn0g08.png" "expectations/pngsuite/xhdn0g08.png.out"
}

@test "[INVALID] xlfn0g04.png" {
    test_png_file "fixtures/pngsuite/xlfn0g04.png" "expectations/pngsuite/xlfn0g04.png.out"
}

@test "[INVALID] xs1n0g01.png" {
    test_png_file "fixtures/pngsuite/xs1n0g01.png" "expectations/pngsuite/xs1n0g01.png.out"
}

@test "[INVALID] xs2n0g01.png" {
    test_png_file "fixtures/pngsuite/xs2n0g01.png" "expectations/pngsuite/xs2n0g01.png.out"
}

@test "[INVALID] xs4n0g01.png" {
    test_png_file "fixtures/pngsuite/xs4n0g01.png" "expectations/pngsuite/xs4n0g01.png.out"
}

@test "[INVALID] xs7n0g01.png" {
    test_png_file "fixtures/pngsuite/xs7n0g01.png" "expectations/pngsuite/xs7n0g01.png.out"
}

@test "[VALID] z00n2c08.png" {
    test_png_file "fixtures/pngsuite/z00n2c08.png" "expectations/pngsuite/z00n2c08.png.out"
}

@test "[VALID] z03n2c08.png" {
    test_png_file "fixtures/pngsuite/z03n2c08.png" "expectations/pngsuite/z03n2c08.png.out"
}

@test "[VALID] z06n2c08.png" {
    test_png_file "fixtures/pngsuite/z06n2c08.png" "expectations/pngsuite/z06n2c08.png.out"
}

@test "[VALID] z09n2c08.png" {
    test_png_file "fixtures/pngsuite/z09n2c08.png" "expectations/pngsuite/z09n2c08.png.out"
}
